services:
  db:
    image: postgres:15
    container_name: postgres_blog_db
    restart: always
    environment:
      POSTGRES_USER: postgres # 👈 Your Postgres username
      POSTGRES_PASSWORD: 123 # 👈 Your Postgres password
      POSTGRES_DB: nest2 # 👈 Your initial database
    ports:
      - '5445:5432' # Expose Postgres on localhost:5432

volumes:
  postgres_data: # Named volume for data persistence
